FROM node:12-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .
RUN npm run build

EXPOSE 9002
CMD [ "npm", "start" ]
# CMD [ "http-server", "dist" ]
# docker build . -t <your username>/node-web
# docker run -p 5001:8080 -d <your username>/node-web
# docker exec -it <container id> /bin/bash
# curl -i localhost:49160 